### PR TITLE
add simple tests to Book.globalPosition

### PR DESCRIPTION
**Pull request by jozic**
i'm total newbie in gradle, and i wasn't even able to build the project from command line on master branch, but it all "magically" builds and works in Android Studio

please let me know if something need to be fixed

### CODE REVIEW

**Comment by jozic** [comment]
@PaulWoitaschek could you please help me to understand the failure on build server?

```
Execution failed for task ':exoplayer-opus:prepareOpus'.
> java.io.IOException: Command tar -xzf "/home/ubuntu/Voice/exoplayer-opus/src/main/jni/opus-1.2.1.tar.gz" -C "/home/ubuntu/Voice/exoplayer-opus/src/main/jni" exited with exitCode=2
```

doesn't look like it's related to the changes, but i'm not sure

**Comment by PaulWoitaschek** [comment]
Thanks a lot for your pull request! Keep sending more of these :)

The build error is not related to your changes but to a url of a dependency that has changed.

**Comment by PaulWoitaschek** [comment]
A small review: I do not prefix tests with `test` as that's redundant due to it's annotation.
Also I removed the randomness which can cause unpredictable test results.

d904f12aa9401201af2ff51c8afaf7748fa99572

**Comment by jozic** [comment]
Thanks for your encouragement Paul! I appreciate it!

in future feel free to comment in PRs directly and I will be happy to fix your comments

**Pull request merged**
