### PR TITLE
Use distinct embedded Cover Image

### LINKED ISSUE #1643: Cover picture
### Overview

i have a directory with many audio book mp3 files of a series, e.g. "die drei Fragezeichen". every mp3 file has its own cover picture. But the app displays always only the cover picture of the first file. i would expect, that always the cover is loaded when a new file is being played.

### How to reproduce

open the app
see the covers pictures

### Version

6.1.2

### Android Version

12

### Device Model

Samsung Galaxy tab a7

### PR DESCRIPTION
**Pull request by theAkito**
* Update Database Schema version.

* Add cover picture property to Chapter data structure.

* Scan for all embedded cover pictures & apply to each chapter.

* Show embedded cover picture of each book's current chapter on homepage.

Resolves #1643.

### CODE REVIEW

**Comment by pecco83** [comment]
If you return to the main screen of the application (list of books), then playback stops.

**Comment by theAkito** [comment]
> If you return to the main screen of the application (list of books), then playback stops.

No. It continues to play all along.

**Comment by theAkito** [comment]
@PaulWoitaschek Would you check this out, please?

**Comment by PaulWoitaschek** [comment]
Thanks for your effort in implementing this. Unfortunately I will close this now due to the reasoning given in the linked issue.

**Pull request closed without merging**
