### PR TITLE
Czech translation created

### PR DESCRIPTION
**Pull request by svetlemodry**

### CODE REVIEW

**Comment by Ph1b** [comment]
Dear svetlemodry, thanks again for your translation!

I just created a [project page](https://www.transifex.com/projects/p/material-audiobook-player/) for translations. Do you want to be the maintainer of the czech language?
There are a few new strings that are still untranslated.

**Comment by svetlemodry** [comment]
Hi! Thanks for the info and yes, would be cool.

**Comment by Ph1b** [comment]
Great! I just added you :)

**Comment by svetlemodry** [comment]
Thanks! Any chance to get me the "reviewer" rights so that I can lock the finalized translated strings?

**Comment by Ph1b** [comment]
Im new to the system. What means lock finalized strings?

**Comment by svetlemodry** [comment]
Details of the Transifex roles can be found here: http://docs.transifex.com/guides/roles

Reviewer
A user that has both translation and reviewing permissions for a specific language. He can either translate, edit an existing translation or mark a translation as reviewed, for quality control reasons. Once a translation is reviewed, it cannot be altered by a non-reviewer translator.

**Pull request merged**
