### PR TITLE
Added new percentage indicator

### PR DESCRIPTION
**Pull request by ivanmgribeiro**
This PR adds a new circular percentage indicator overlaid on the bottom right of the book cover.
Suggested in #834

### CODE REVIEW

**Comment by GitBugit** [comment]
Could you also integrate a progress bar showing how much time is remaining etc

**Comment by test2a** [comment]
@gitbugit

https://ibb.co/R6TjC9V

We already have a progress bar below each book that shows the progress. I dont know what more are you asking for ? Maybe in the book page?

**Comment by GitBugit** [comment]
@test2a 🤦‍♂️ I had the wrong layout, didn't know that a different layout shows the time. But this is exactly what I meant so my bad

**Comment by test2a** [comment]
@GitBugit not a problem

**Comment by PaulWoitaschek** [comment]
Sorry but this won't get merged. The implementation looks really good an clean so kudos for that. However I think the new slider implemenation from the material components is good enough to pick granular values.

**Comment by robertmarsal** [comment]
Hi @PaulWoitaschek this is a feature I am interested in myself and I see a couple of requests in the issue tracker for it as well so can I please check that you closed the right PR as your comment mentions picking values in a slider but this PR is about displaying the completion percentage of a book (unless I am wrong)?

Thanks

**Comment by PaulWoitaschek** [comment]
Ah these were two different issues indeed. I'll answer in the linked issue.

**Pull request closed without merging**
