### PR TITLE
Implementing playlists in MediaSession

### PR DESCRIPTION
**Pull request by Eifelschaf**
These commits contain an implementation of playlists in the mediasession. The playlist for each book consists of it's chapters and will only be displayed if there is more than one chapter. 

Additionally I fixed one of the test classes.

### CODE REVIEW

**Comment by PaulWoitaschek** [comment]
So did that actually work for you? If I understand correctly, the `CHAPTER_ID` was never parsed so I think I fixed it in 
d85aa6b495abec3e11b150260f2ec1ab4978e33e

Also in this block:

```kotlin
      BookUriConverter.CHAPTER_ID -> {
        val id = bookUriConverter.extractBook(uri)
        currentBookIdPref.value = id
        onPlay()
      }
```
shouldn't the chapter id also be parsed so this can work correctly?

**Comment by Eifelschaf** [comment]
Actually this is just to have unique IDs. What's used for playback is the
numeric item id in the playlist

Paul Woitaschek <notifications@github.com> schrieb am So., 15. Okt. 2017,
21:51:

**Comment by Eifelschaf** [comment]
Works really well by the way.

Matthias Kutscheid <eifelschaf@gmail.com> schrieb am So., 15. Okt. 2017,
21:55:

**Comment by PaulWoitaschek** [comment]
Hm, for me not. It does not show the book contents but only the chapters after the current chapter. So there is no way for navigating tracks back from android auto.

**Comment by Eifelschaf** [comment]
Yeah, that's an auto thing. And this is also why I left the skip back
action in. On wear we see the whole list. Do you test with the simulated
head unit or phone app? Because in the phone app I can't see the extra
actions.

Paul Woitaschek <notifications@github.com> schrieb am So., 15. Okt. 2017,
22:53:

**Pull request merged**
