### PR TITLE
Feature/sleep fade

### PR DESCRIPTION
**Pull request by mtvjr**
Added an audio fade as the sleep timer approaches 0.

### CODE REVIEW

**Comment by thigg** [comment]
Will this be merged?

**Comment by mtvjr** [comment]
I haven't made any attempt to keep it up to date since I received no response from the initial pull request. But if there is interest I can try to find time to fix the conflicts.

**Comment by thigg** [comment]
I'd like to see this feature

**Comment by PaulWoitaschek** [comment]
Thanks a lot for the PR!

I implemented it a bit differently as I did not want to duplciate the skip logic from the MediaPlayer.
However now that I'm reviewing your code once again, I might have just accepted the PR.

**Comment by PaulWoitaschek** [comment]
Just did a major refactoring: 644c4bf65851dfd0bed75acdc2688c340e3470df
A review would be welcome!

**Pull request closed without merging**
